import { Lead, Client, DashboardStats, Message } from './types';

export const mockStats: DashboardStats = {
  leadsContacted: 1247,
  leadsContactedChange: 12.5,
  uniqueLeads: 892,
  uniqueLeadsChange: 8.3,
  messagesSent: 4521,
  messagesSentChange: 15.2,
  responseRate: 68.4,
  responseRateChange: 3.1,
  bookings: 156,
  bookingsChange: 22.7,
};

export const mockLeads: Lead[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    username: '@sarahjohnson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    status: 'qualified',
    lastMessage: 'I would love to learn more about your services!',
    lastMessageTime: '2 min ago',
    responseTime: 4.2,
    conversationCount: 8,
    showsBookingIntent: true,
    tags: ['High Intent', 'Interested'],
  },
  {
    id: '2',
    name: 'Mike Chen',
    username: '@mikechen_fit',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
    status: 'engaged',
    lastMessage: 'What are your prices?',
    lastMessageTime: '15 min ago',
    responseTime: 5.1,
    conversationCount: 4,
    tags: ['Price Inquiry'],
  },
  {
    id: '3',
    name: 'Emma Williams',
    username: '@emmawilliams',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    status: 'booked',
    lastMessage: 'Yes, Tuesday at 3pm works perfectly!',
    lastMessageTime: '1 hour ago',
    responseTime: 3.8,
    conversationCount: 12,
    showsBookingIntent: true,
    tags: ['Booked', 'Confirmed'],
  },
  {
    id: '4',
    name: 'James Rodriguez',
    username: '@jamesrod',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=James',
    status: 'new',
    lastMessage: 'Hi! Just saw your post',
    lastMessageTime: '30 min ago',
    conversationCount: 1,
    tags: ['New Lead'],
  },
  {
    id: '5',
    name: 'Lisa Park',
    username: '@lisapark_style',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lisa',
    status: 'engaged',
    lastMessage: 'Can you tell me more about the process?',
    lastMessageTime: '45 min ago',
    responseTime: 6.2,
    conversationCount: 5,
    isFollowup: true,
    tags: ['Follow Up Needed'],
  },
  {
    id: '6',
    name: 'David Kim',
    username: '@davidkim',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=David',
    status: 'converted',
    lastMessage: 'Thank you so much! The session was amazing!',
    lastMessageTime: '2 hours ago',
    responseTime: 4.5,
    conversationCount: 18,
    tags: ['Converted', 'VIP'],
  },
  {
    id: '7',
    name: 'Olivia Brown',
    username: '@oliviab',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Olivia',
    status: 'qualified',
    lastMessage: 'I am ready to book!',
    lastMessageTime: '3 hours ago',
    responseTime: 5.8,
    conversationCount: 9,
    showsBookingIntent: true,
    tags: ['High Intent', 'Ready to Book'],
  },
  {
    id: '8',
    name: 'Alex Turner',
    username: '@alexturner',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    status: 'engaged',
    lastMessage: 'Let me think about it',
    lastMessageTime: '5 hours ago',
    responseTime: 7.2,
    conversationCount: 6,
    isFollowup: true,
    tags: ['Needs Follow Up'],
  },
];

export const mockClients: Client[] = [
  {
    id: '1',
    businessName: 'FitLife Coaching',
    email: 'coach@fitlife.com',
    instagramHandle: '@fitlife_coaching',
    isConnected: true,
    leadsCount: 342,
    conversionRate: 18.5,
    createdAt: '2024-01-15',
    aiPrompts: {
      greeting: 'Hey! Thanks for reaching out! 💪',
      qualification: 'What are your fitness goals?',
      booking: 'Would you like to schedule a free consultation?',
    },
  },
  {
    id: '2',
    businessName: 'Beauty by Maya',
    email: 'maya@beautybymaya.com',
    instagramHandle: '@beautybymaya',
    isConnected: true,
    leadsCount: 528,
    conversionRate: 24.2,
    createdAt: '2024-02-20',
    aiPrompts: {
      greeting: 'Hi gorgeous! 💄 Thanks for the message!',
      qualification: 'What service are you interested in?',
      booking: 'I have some openings this week!',
    },
  },
  {
    id: '3',
    businessName: 'Tech Solutions Pro',
    email: 'info@techsolutions.com',
    instagramHandle: '@techsolutionspro',
    isConnected: false,
    leadsCount: 156,
    conversionRate: 12.8,
    createdAt: '2024-03-01',
  },
  {
    id: '4',
    businessName: 'Wellness Studio',
    email: 'hello@wellnessstudio.com',
    instagramHandle: '@wellness_studio',
    isConnected: true,
    leadsCount: 892,
    conversionRate: 31.4,
    createdAt: '2023-11-10',
  },
];

export const mockMessages: Message[] = [
  { id: '1', content: 'Hi! I saw your post about fitness coaching', sender: 'lead', timestamp: '10:30 AM' },
  { id: '2', content: 'Hey! Thanks for reaching out! 💪 I would love to help you on your fitness journey. What are your main goals?', sender: 'ai', timestamp: '10:30 AM' },
  { id: '3', content: 'I want to lose weight and build muscle', sender: 'lead', timestamp: '10:32 AM' },
  { id: '4', content: 'That is awesome! Those are great goals. I specialize in body recomposition which combines fat loss with muscle building. Have you worked with a trainer before?', sender: 'ai', timestamp: '10:32 AM' },
  { id: '5', content: 'No, this would be my first time', sender: 'lead', timestamp: '10:35 AM' },
  { id: '6', content: 'Perfect! I love working with beginners - we can build a solid foundation together. Would you be interested in a free 30-minute consultation to discuss your goals in detail?', sender: 'ai', timestamp: '10:35 AM' },
  { id: '7', content: 'Yes! That sounds great!', sender: 'lead', timestamp: '10:38 AM' },
  { id: '8', content: 'Amazing! 🎉 I have availability this Tuesday at 3pm or Thursday at 5pm. Which works better for you?', sender: 'ai', timestamp: '10:38 AM' },
];

export const chartData = [
  { name: 'Mon', leads: 24, messages: 120, conversions: 4 },
  { name: 'Tue', leads: 35, messages: 180, conversions: 7 },
  { name: 'Wed', leads: 28, messages: 150, conversions: 5 },
  { name: 'Thu', leads: 42, messages: 210, conversions: 9 },
  { name: 'Fri', leads: 38, messages: 190, conversions: 8 },
  { name: 'Sat', leads: 45, messages: 230, conversions: 11 },
  { name: 'Sun', leads: 32, messages: 160, conversions: 6 },
];

export const conversionFunnelData = [
  { name: 'New Leads', value: 892, fill: 'hsl(187, 85%, 53%)' },
  { name: 'Engaged', value: 654, fill: 'hsl(160, 84%, 39%)' },
  { name: 'Qualified', value: 342, fill: 'hsl(38, 92%, 50%)' },
  { name: 'Booked', value: 156, fill: 'hsl(280, 65%, 60%)' },
  { name: 'Converted', value: 89, fill: 'hsl(340, 75%, 55%)' },
];
